### ISSUE TITLE
Can not read property name of null

### ISSUE THREAD

**Issue by tuanv2t** [WaftTech/WaftEngine#21]
https://gyazo.com/ebff69b66a9724f1d29897054562c46f
![ebff69b66a9724f1d29897054562c46f](https://user-images.githubusercontent.com/8486393/64811901-59e70a80-d5c8-11e9-8f7f-1865b9442670.png)

=> Error in \client\app\components\CategoryElement\index.js

**Comment by mkmpvtltd1** [comment]
https://github.com/WaftTech/WaftEngine/commit/1ef09901b75f2f9f5e6383f35d0e4b310001f4ad
Commit fixed the issue
